# Generated by Django 5.2.1 on 2025-05-22 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255, unique=True)),
                ('nutrition_data', models.JSONField(help_text='Stores calories, protein, carbs, fat, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Food Nutrition Data',
                'indexes': [models.Index(fields=['food_name'], name='api_foodnut_food_na_d58935_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', help_text="User's self-identified gender", max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('active', 'Very Active'), ('extra', 'Extra Active')], max_length=20)),
                ('fitness_goal', models.CharField(choices=[('loss', 'Weight Loss'), ('gain', 'Muscle Gain'), ('maintain', 'Maintenance'), ('fitness', 'General Fitness')], default='maintenance', max_length=20)),
                ('vegan_preference', models.BooleanField(default=False)),
                ('dietary_preferences', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='analysis_images/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_result', models.JSONField(blank=True, help_text='Raw analysis from AI model', null=True)),
                ('nutrition_data', models.JSONField(blank=True, help_text='Processed nutrition information', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Image Analyses',
                'indexes': [models.Index(fields=['uploaded_at'], name='api_imagean_uploade_55a021_idx'), models.Index(fields=['user'], name='api_imagean_user_id_edb2c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dietary_preferences', models.CharField(max_length=255)),
                ('fitness_goal', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Muscle Gain', 'Muscle Gain'), ('Maintenance', 'Maintenance'), ('General Fitness', 'General Fitness')], max_length=20)),
                ('activity_level', models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly Active', 'Lightly Active'), ('Moderately Active', 'Moderately Active'), ('Very Active', 'Very Active'), ('Extra Active', 'Extra Active')], max_length=20)),
                ('vegan_preference', models.BooleanField(default=False)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('plan_data', models.JSONField(help_text='Stores generated meal plan structure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='api_mealpla_created_045902_idx'), models.Index(fields=['user'], name='api_mealpla_user_id_1cfe62_idx')],
            },
        ),
    ]
